// <auto-generated />
using AgendaDeTarefas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaDeTarefas.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20230306003355_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgendaDeTarefas.Models.TarefaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tarefa_Finalizada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("data")
                        .HasColumnType("int");

                    b.Property<int>("fim")
                        .HasColumnType("int");

                    b.Property<int>("inicio")
                        .HasColumnType("int");

                    b.Property<int>("nome")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TarefaModel");
                });
#pragma warning restore 612, 618
        }
    }
}
